---
title: 'Session 3: KS1 ''Storytelling'' training – Investigating resources'
hero_image: images/introduction3.png
description: Session 3 of the online training course introduces teachers to some resources
  for the KS1 'Storytelling' Teaching Approach trial through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: '2020-09-08'
steps:
- title: Tasks in ScratchJr
- title: 'Task 1: Drawing ideas'
- title: 'Task 2: ScratchJr interface and blocks'
- title: 'Task 3: ScratchJr blocks: Questions and answers'
- title: 'Task 4: Drawing in ScratchJr'
- title: 'Task 5: Sharing projects'
- title: 'Task 6: Completion survey'
